site_name: Sonetel Python SDK

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides:
    - How-To Buy a Number: how-to-guides/buy-number.md
    - How-To Make a Call: how-to-guides/make-call.md
    - How to Get Prepaid balance: how-to-guides/get-prepaid-balance.md
  - reference.md
  - explanation.md